export default {
	SET_SETTINGS: 'SETTINGS:SET',
	SET_SEX: 'SETTINGS:SET_SEX',

	SHOW_PAGE: 'PAGE:SHOW',

	BUTTON_SEX_NEXT_ENABLE: 'BUTTON:SEX:NEXT:ENABLE',

	QUIZ_START: 'QUIZ:FIRST_STEP',
	QUIZ_NEXT_STEP: 'QUIZ:NEXT_STEP',
	

};
