export default {
	SET_SETTINGS: 'SETTINGS:SET',
	SET_SEX: 'SETTINGS:SET_SEX',

	SHOW_PAGE: 'PAGE:SHOW',
	SHOW_RESULTS: 'PAGE:RESULTS',

	BUTTON_SEX_NEXT_ENABLE: 'BUTTON:SEX:NEXT:ENABLE',

	QUIZ_START: 'QUIZ:FIRST_STEP',
	QUIZ_NEXT_STEP: 'QUIZ:NEXT_STEP',

	SHOW_LOADER: 'LOADER:SHOW',
	HIDE_LOADER: 'LOADER:HIDE',
	
	SET_SHARES: 'SHARES:SET',
	PUBLIC_SHARE: 'SHARES:PUBLIC',


};
